name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根据需要指定 Node.js 版本

      - name: Install dependencies
        run: |
          npm install @libsql/client@^0.4.0 \
            axios@^1.6.2 \
            cors@^2.8.5 \
            dotenv@^16.3.1 \
            express@^4.18.2 \
            express-rate-limit@^7.1.5 \
            file-type@^18.7.0 \
            multer@^1.4.5-lts.1 \
            node-schedule@^2.1.1 \
            sharp@^0.33.1 \
            uuid@^9.0.1

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add package-lock.json
          git commit -m "Install dependencies" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的令牌进行身份验证
